### ISSUE TITLE
Add more fonts by default

### ISSUE THREAD

**Issue by trufae** [trufae/Therm#10]
Default font is fine, but will be good to have some extra fonts that are usually installed by programmers or old-school nostalgics.

* IBM fonts
* Ubuntu/Android Console
* Profont
* Firacode (have ligatures)

Please share your thoughs on this.

http://hivelogic.com/articles/top-10-programming-fonts/

**Comment by trufae** [comment]
https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/GeneralPurposeKeys.html#//apple_ref/doc/uid/TP40009253-SW8

**Comment by trufae** [comment]
https://github.com/chrissimpkins/codeface/tree/master/fonts
https://int10h.org/oldschool-pc-fonts/fontlist/

**Comment by trufae** [comment]
[agave-r.ttf.zip](https://github.com/trufae/Therm/files/1489328/agave-r.ttf.zip)

**Comment by trufae** [comment]
[ProggySquare.ttf.zip](https://github.com/trufae/Therm/files/1489331/ProggySquare.ttf.zip)
[PxPlus_IBM_MDA.ttf.zip](https://github.com/trufae/Therm/files/1489334/PxPlus_IBM_MDA.ttf.zip)

**Comment by trufae** [comment]
Please send pullreqs with more fonts into the fonts/ directory if you want them to be included in next releases

**Comment by joanbono** [comment]
Would you mind to include (for example) the Powerline Symbols?

**Comment by trufae** [comment]
Send a pullreq or link to the file please

**Comment by joanbono** [comment]
Done.

PR #30
