### ISSUE TITLE
“Therm” is damaged and can’t be opened.

### ISSUE THREAD

**Issue by jedisct1** [trufae/Therm#14]
Hi Trufae!

Looks like something is missing in the precompiled Therm 0.0.2 binary.

Trying to run it results in `“Therm” is damaged and can’t be opened. You should move it to the Trash`.

That's on High Sierra.

**Comment by trufae** [comment]
Oh! I will check this out later tonight and push a new build. I have another bug to catch out too.

Thanks

**Comment by trufae** [comment]
Please try 0.0.3

**Comment by jedisct1** [comment]
Yep, that one works perfectly!

Thanks!
