### ISSUE TITLE
Tab list

### ISSUE THREAD

**Issue by joanbono** [trufae/Therm#16]
Hi @pancake

I can open new tabs by pressing  `cmd+t` and switch between them with `cmd+1` or `cmd+2` but I cannot see the tab list (in iTerm I think it's possible by pressing `Shift+cmd+t`). 

Are you planning to add this or it's removed in purpose? 

Cheers

**Comment by trufae** [comment]
I removed them on purpose. I have in mind a minimalistic view of them of 1 pixel line. But definiveliy not colorized or with titles. My usual workflow is a fullscreen terminal and having tabs is a loss of screen that barely matters to me (and the other users i have asked for). Which is your workflow? Maybe we can find a better midpoint solution

**Comment by joanbono** [comment]
Well maybe I was thinking about a tmux tab style, but easy to move between them as iTerm allows. But if you are not planning to add this, I can work with tmux tabs.

By the way, maybe that one-pixel size tab with a different color will be fine. I mean, a single pixel line on the top for Therm window. One tab, one single pixel line fron right to left. Two tabs, the same line with a 2 or 3 pixel separation in the middle, for 3 tabs, three lines... And change the color of the line of the focused tab... this will be really awesome, because user will know how many tabs opened has.

**Comment by joanbono** [comment]
Hi @pancake , I was thinking in something like:

+ For one tab

![](https://i.imgur.com/dOAxuKB.png)

+ Two tabs (actual tab is the one with the cyan line)

![](https://i.imgur.com/RhziEXv.png)

+ Three tabs

![](https://i.imgur.com/kukGlaW.png)

With this single line is possible to know how many tabs and in which tab are you working in.

By the way, this is a suggestion, if you are not planning to add it, I'll use tmux instead, no worries 😃

**Comment by trufae** [comment]
Yes. That was exactly what i was in mind :)

Cool to see that we are in the same page.

Just one question. Do u use the tmux integration in iterm?

**Comment by joanbono** [comment]
> Just one question. Do u use the tmux integration in iterm?

No, I don't

**Comment by trufae** [comment]
also, the fullscreen indicator has been removed to avoid noise, but we can bring it back in a clean way by using this one liner approach

**Comment by trufae** [comment]
Check the 0.0.9 release https://github.com/trufae/Therm/releases/tag/0.0.9

**Comment by joanbono** [comment]
YIIIIIIIIIIIIIIIIIIIIHAAAAAAAAAAAAAAAAAAAAAAAAAAAAA!!!!!!!!!!!!!!!!!!!!

AWESOME :D!!!!

**Comment by trufae** [comment]
I’ll improve them, but i think this is way less intrussive and handy that standard tabs. At least for a terminal :)
