### ISSUE TITLE
New update pop-up

### ISSUE THREAD

**Issue by joanbono** [trufae/Therm#23]
Hi @trufae 

Therm "suggest" me to update the `Therm` version. Should I or it will install `iTerm2`?

![image](https://user-images.githubusercontent.com/7288621/33232316-5d3d06f4-d204-11e7-983f-ec6c71c24c53.png)

**Comment by trufae** [comment]
The update dialog must die. I have already commited some rebrandings in other places after the last release. I dont plan to maintain updates. I never trusted automatic updates and i prefer to let users download and verify what they install properly. Also. At some point it will be better to just put therm in the appstore and let apple manage the updates and not the app itself

**Comment by joanbono** [comment]
OK, thanks!

**Comment by trufae** [comment]
Ive killed the sparkle dependency in git (the one who managed updates). Ill release after some more rebrandings and tweaks i have in mind. Probably today
