### ISSUE TITLE
Therm crashes whit zsh

### ISSUE THREAD

**Issue by joanbono** [trufae/Therm#27]
Hi @trufae 

**Therm** crashes when executing `zsh`.

While doing:

~~~bash
jbono@MacBook [~]> zsh
~~~

**Therm** closes immediately and suggests to send a crash report.

I don't know if this is useful for you but I pasted the report to [paste.ee](https://paste.ee/p/IshW7)

**Edit**:

Also crashes with a simple `echo`:

~~~bash
jbono@MacBook [~]> echo "Hola"
~~~

**Comment by trufae** [comment]
Please specify the version

**Comment by joanbono** [comment]
It's `v0.0.7`, downloaded few minutes ago.

**Comment by trufae** [comment]
Happens in 0.0.6 too?

**Comment by joanbono** [comment]
Nope, `v.0.0.6` works like a charm.

**Comment by trufae** [comment]
cant reproduce with 0.0.7, but seems like something related to the commandline parsing magic that iterm does and i have purged half of it and some selectors are still being called. ill try to do a blind fix, can you test from git? or do you want me to push a build here?

**Comment by trufae** [comment]
try this build, i did a blind fix

[Therm.app.zip](https://github.com/trufae/Therm/files/1506601/Therm.app.zip)

**Comment by joanbono** [comment]
It works now! 😃 

Thanks @trufae !

**Comment by trufae** [comment]
Thanks for testing :) ill push another release just for this.

**Comment by trufae** [comment]
https://github.com/trufae/Therm/releases/tag/0.0.8

**Comment by joanbono** [comment]
`v0.0.8` downloaded and tested. Everything works as expected 👍 

Thanks!
