### ISSUE TITLE
Remove or change the expose feature

### ISSUE THREAD

**Issue by trufae** [trufae/Therm#29]
it's slow, inconsistent with the OS animations and probably nobody uses it.

feedback on this pls

**Comment by novia713** [comment]
kill 'em all

**Comment by trufae** [comment]
ive removed the animations

**Comment by trufae** [comment]
but the feature looks crappy to me, so its probably better to kill it, what do other therm users think?

**Comment by joanbono** [comment]
I think is useless (at least for me)... Before this issue I didn't know about this feature xD

**Comment by trufae** [comment]
ok, i will kill it :D
