### ISSUE TITLE
Make brew package

### ISSUE THREAD

**Issue by trufae** [trufae/Therm#32]
https://github.com/caskroom/homebrew-cask/pull/41645/files

**Comment by MindTooth** [comment]
https://github.com/caskroom/homebrew-cask/pull/43055

**Comment by trufae** [comment]
Oops!

https://github.com/caskroom/homebrew-cask/pull/43055

**Comment by novia713** [comment]
@trufae @MindTooth https://github.com/caskroom/homebrew-cask/pull/43055/commits/f650d99b9a3f051ec14b8f744693cd036812c7ae

**Comment by trufae** [comment]
We can close this now :)

`brew install caskroom/cask/therm`

thanks!
