### ISSUE TITLE
Fullscreen, but still show the menbar

### ISSUE THREAD

**Issue by MindTooth** [trufae/Therm#36]
Hi,

I would love to have a fullscreen option that showed the window decoration, and still open in fullscreen.  The hacking solution now is to set the term size outside the viewport.

Also, it would be nice to have an option so that the windows size is remember, e.g. using Moom or Spectacle.

**Comment by trufae** [comment]
there’s an option in preferences to show menubar in fullscreen or not, just change that option

**Comment by MindTooth** [comment]
Found out how to solve this.  Thanks!
