### ISSUE TITLE
Therm window steals focus, making it impossible to right click Dock item and pick option

### ISSUE THREAD

**Issue by MindTooth** [trufae/Therm#37]
Hi,

Noticed yesterday that Therm steals the focus when hovering making it impossible to right click its icon in the Dock and close e.g.  The menu just closes itself.

Thought it to be WeeChat yesterday, but the same occurred today with a regular window.

Any ideas?

**Comment by trufae** [comment]
I use the keyboard when this happens. Other solutions will make therm slowly responsive or change the config of the dock. Its anoying but i cant think of a better solution without dropping the hover

**Comment by MindTooth** [comment]
At least it's known ;)
