### ISSUE TITLE
"Focus Follows Mouse" settings are ignored

### ISSUE THREAD

**Issue by zakx** [trufae/Therm#42]
In the advanced settings, "steal key focus even when inactive" is set to no (by default as it seems). However, the application windows still do steal key focus when inactive.

I've tried disabling "Focus follows Mouse" completely, but that doesn't work either. I also tried setting "steal key focus…" to yes, and to no again, and restarted, which also had no effect.

I'm running Version 0.1.5.

**Comment by trufae** [comment]
yes, it’s hardcoded in the code on purpose, settings are not cleanedup completely. there are settings that i dont want to have them as option, mainly because having to tap to get focus in the root of many confusions and lack of performance when using the terminal. at least in my workflow

**Comment by zakx** [comment]
I see, thanks for the clarification.

**Comment by tostr7191** [comment]
Could you reconsider adding a (working) option? I dislike focus follows mouse, but like therm a lot as a slimmed down version of iTerm. Also I think FFM is such a polar feature, either you hate it with a passion or you can't live without it. It's probably a good idea to make something like this configurable :)
