### ISSUE TITLE
make titlebar same color as background

### ISSUE THREAD

**Issue by novia713** [trufae/Therm#44]
in regarding of a more stylish appearing, titlebar should be same color as background
now the titlebar is a bit more clear than the background

**Comment by trufae** [comment]
yeah sounds reasonable. i did that tone change on purpose to make it easier to identify when not in fullscreen, same goes for window borders

**Comment by novia713** [comment]
i think the item itself and its area is quite well denoted by the close, minimize, maximize buttons and the title window text
i think that is enough to identify when we are in fullscreen or not, and where to pick with the mouse in order to drag & drop

**Comment by trufae** [comment]
Fixed in bd8fd8b1eb35fcfaad40f0b0a98880cd78387bf1
