### ISSUE TITLE
Switching between panes not working at all on Cmd + [ or ]

### ISSUE THREAD

**Issue by poige** [trufae/Therm#47]

**Comment by trufae** [comment]
use cmd+jk or change the settings, i use unix-friendly keys

**Comment by poige** [comment]
Vi-friendly you meant in fact. Well, except favourite editors' there're platform specific short-cuts users are used to.

**Comment by trufae** [comment]
And window managers. Dwm works like that. Anyway, if u change the config it may work. Let me know if you cant. But one of the reasons of the fork was to have good defaults for me so i dont have to spent half an hour touching options to feel comfortable in it

**Comment by trufae** [comment]
Which other app/tool/wm uses [] to select next/prev pane? A part from iterm?

**Comment by poige** [comment]
No idea. But obviously lots of them use Cmd_{ } thus only adding press of Shit to aforementioned short-cut.

**Comment by trufae** [comment]
never find any, or even find it intuitive, HJKL exists for a reason

**Comment by poige** [comment]
it's plainly nonsense. Pressing [, ] and even {, } with Cmd is easier can be done even w/ just one (right) hand. Your idealising of HJKL is somewhat pretty silly but well, ok, it's your right anyways.

**Comment by trufae** [comment]
You can change the keys in settings. The {}[] keys are pure crap in many layouts. And btw, do u know the reason for hjkl and why its used so widely? 

I dont know how tiny your hands are but hjkl is closer to cmd than []{} and hjkl keys  dont require modifiers to be used. Remember that in this planet there are more languages than just english. And to use cmd+[]{} i need to press 3 keys which is not possible with my hands.

Hjkl is in the same place in all layouts, its universal and closer to the rest of keys than []{} so it requires less hand movements. Therefor its more efficient.

**Comment by poige** [comment]
Pretty ridiculous statements all-in-all. Cmd_[/{ isn't working in English only in case you didn't know. With Cmd_[{ one doesn't need to bend his fingers of right hands — just put it straight on keyboard and you will see — the buttons are directly under your fingertips. Completely different to what you'll have to press Cmd_H, for e. g.

> And btw, do u know the reason for hjkl and why its used so widely?

I'm using Linux since 1998 or so; still I don't miss the time when people had primitive teletype keyboard with arrows put on HJKL. Also, pay attention — when you use vim you switch between modes and don't have to keep anything pressed while you click on HJKL.

**Comment by trufae** [comment]
You can change the default settings, this is just a matter of taste, there's no point in continue discussing this.

And yes, vim does hjkl because it have MODES, which terminals dont have. And i use HJKL for moving panes, which is more consistent with DWM or many other tiling window managers, and are the same keys i use by default in Therm and in many other programs.
