### ISSUE TITLE
Menus from Dock or Menu Bar are closed automatically when moving mouse over Therm window

### ISSUE THREAD

**Issue by thestr4ng3r** [trufae/Therm#53]
See
![thermfail2](https://user-images.githubusercontent.com/1460997/42327423-f26bbf84-806b-11e8-9c0d-81cff6cf4a50.gif)

The menu disappears right when the mouse enters the Therm window without clicking or anything.
This is especially annoying when Therm is maximized, because of the small gap between the menu and the dock, the right-click menu is almost impossible to use.

macOS is 10.13.5 (17F77) using Therm 0.1.8 from Homebrew.

**Comment by trufae** [comment]
This has been reported severa times already. Do you know in which version of therm the regression was introduced? Can you try previous releases?

**Comment by thestr4ng3r** [comment]
I will check the next time I am on a mac.

**Comment by trufae** [comment]
This issue is also found in iTerm2

https://gitlab.com/gnachman/iterm2/issues/6734

**Comment by phallguy** [comment]
I have this issue as well and noticed some odd issues with some other windows. I believe this may have something to do with the 'Focus follows mouse' option. I've tried disabling it but it appears that option is hard coded on in therm.

I'm using 0.1.9 via Homebrew

**Comment by trufae** [comment]
Seems to work better in mojave. Did you upgraded?

**Comment by phallguy** [comment]
Yes this is happening on Mojave.
