### ISSUE TITLE
'Save Currrent Settings to Folder' feature crashes when set

### ISSUE THREAD

**Issue by peterlobster** [trufae/Therm#60]
When I try to set a folder to 'Save Current Settings to Folder', it doesn't save. It doesn't work if I don't set the folder and try to use the 'Home' folder.

![screen shot 2018-12-01 at 3 45 22 pm](https://user-images.githubusercontent.com/38382145/49334057-668dfb00-f580-11e8-800d-8d291aec12a3.png)

**Comment by trufae** [comment]
I think I have removed this option. try removing the default settings and updating to the last version.

**Comment by peterlobster** [comment]
Awesome! Thank you! 🙏 Does this also mean Threm no longer has the tmux integration? Can't remember if it had it in the first place...

**Comment by trufae** [comment]
Yes . Im killing the tmux integration. Ive been asking for a long time and i still dont know anyone who sees value on this feature
