### ISSUE TITLE
Services menu item displays 'iTerm2' instead of 'Therm'

### ISSUE THREAD

**Issue by peterlobster** [trufae/Therm#67]
Upon installed Therm, a service item gets added to the services menu; however, it incorrectly displays as 'iTerm2' instead of 'Therm'.  If you had 'iTerm2' already installed then, you'll have duplicates as shown below...

![Screen Shot 2019-07-29 at 9 30 25 PM](https://user-images.githubusercontent.com/38382145/62100943-757c9880-b248-11e9-87d4-16c85effd4f5.png)

**Comment by trufae** [comment]
It was fixed in git. Right after the 0.3.1 release
