### ISSUE TITLE
App versions do not match releases

### ISSUE THREAD

**Issue by vitorgalvao** [trufae/Therm#71]
To accurately display version information, macOS apps need to have the `CFBundleVersion` and `CFBundleShortVersionString` tags in `Info.plist`.

Therm has them, but they’re set to `unknown` (literally that string, `CFBundleGetInfoString` is the same).

If versions aren’t set during the build process, they can be added after it’s done by directly editing the `Info.plist`:

```bash
# Change these values
app_path='/PATH/TO/APP/HERE'
app_version='VERSION NUMBER HERE'

# Keep these as they are
/usr/libexec/PlistBuddy -c "Set :CFBundleVersion string ${app_version}" "${app_path}/Contents/Info.plist"
/usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString string ${app_version}" "${app_path}/Contents/Info.plist"
```

That would use the same version number for both fields. Technically they should be different, but that’s a secondary concern. An accurate version number is important for macOS to know which app to open in ambiguous situations; for users who expect the information available via the Finder; and for interoperability with other apps.

**Comment by core-code** [comment]
still broken in 0.6
<img width="624" alt="Screenshot 2023-12-05 at 17 54 57" src="https://github.com/trufae/Therm/assets/1261954/a694aa5b-bb63-440d-b719-2c8c791cd16c">
<img width="255" alt="Screenshot 2023-12-05 at 17 54 44" src="https://github.com/trufae/Therm/assets/1261954/f1ad468f-659a-4713-bab4-f97d45983b47">

**Comment by trufae** [comment]
Would you like to submit a PR?

**Comment by core-code** [comment]
thanks!
