### ISSUE TITLE
Plan to support MacOS versions before 13?

### ISSUE THREAD

**Issue by jmcantrell** [trufae/Therm#74]

**Comment by trufae** [comment]
The 0.5 build should work. Ill try to lower the minos version when i get rid of all the deprecation apis and bump a new build for the 0.6.x series anytime soon. Any specific version you are interested on?

**Comment by jmcantrell** [comment]
My old macbook is running 12.7.1

**Comment by trufae** [comment]
i lowered the version to 12 and seems like its not breaking anything. i want to fix a couple of bugs people reported me in private and i'll do a new release! thank you!

**Comment by trufae** [comment]
check this https://github.com/trufae/Therm/releases/tag/0.6.1
