### ISSUE TITLE
Terminal launches in fullscreen but has 80 x 25 column/row constraints by default

### ISSUE THREAD

**Issue by lexpierce** [trufae/Therm#76]
See screenshot, but until you shrink and then regrow terminal, it launches fullscreen with artificially constrained rows and columns

<img width="1280" alt="Screenshot 2024-02-17 at 10 36 51 PM" src="https://github.com/trufae/Therm/assets/5649235/3f2ec088-bf19-4c24-9d0d-0d2ef0c13c9f">

**Comment by trufae** [comment]
should be fixed in 0.6.2 can you confirm?

**Comment by lexpierce** [comment]
Yes, the full screen issue is fixed.

**Comment by trufae** [comment]
Thanks for confirming!
