### ISSUE TITLE
Brew SHA256 mismatch

### ISSUE THREAD

**Issue by jlongman** [trufae/Therm#80]
Apologies if you don't maintain the Brew resources as well, but upon `brew install therm`:

```
± brew install therm
==> Downloading https://github.com/trufae/Therm/releases/download/0.6.4/Therm-0.6.4.zip
==> Downloading from https://objects.githubusercontent.com/github-production-release-asset-2e65be/104355494/c9c8d4a5-2e23-4936-8f7d-e5169070649d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-A
##...## 100.0%
Error: SHA256 mismatch
Expected: 96ea558143ae60de68eecbfcd9e70aaeab2901d852189ef364ed2e6fc269d055
  Actual: 30b1c67a1d297f5e05de47faa66d6cf118c5a450aac2f222098e4fb1cf80d650
    File: /Users/me/Library/Caches/Homebrew/downloads/56649bcaba9bafb6c9437be368e2cc21b71e1657270394ec7290b1ca61eb0f7e--Therm-0.6.4.zip
To retry an incomplete download, remove the file above.
```
I did delete the file and retry just-in-case but the same issue persisted.

Looking at https://formulae.brew.sh/cask/therm the `96ea...`, not `30b1c...`, appears to be authorative:
- [Homebrew/homebrew-cask/.../therm.rb](https://github.com/Homebrew/homebrew-cask/blob/0ff51c0b3e0903eef5172797bf7d5f9cd5f9d203/Casks/t/therm.rb)
- https://formulae.brew.sh/api/cask/therm.json

**Comment by trufae** [comment]
Nope im not maintaining that package, you can probably submit a PR fixing the sha256, ive updated the blob the very same day the release was done because the previous zip was broken. But seems like brew is faster

**Comment by jlongman** [comment]
So I re-ran the `brew` command today and it worked, then I got paranoid so I downloaded it from here and:
```
 % sha256sum ~/Downloads/Therm-0.6.4.zip                                                                                                   mv-configs/override (master ⚡) MV-MB-003
**30b1c67a1d297f5e05de47faa66d6cf118c5a450aac2f222098e4fb1cf80d650**  /Users/me/Downloads/Therm-0.6.4.zip
 % sha256sum  /Users/me/Library/Caches/Homebrew/downloads/56649bcaba9bafb6c9437be368e2cc21b71e1657270394ec7290b1ca61eb0f7e--Therm-0.6.4.zip
**30b1c67a1d297f5e05de47faa66d6cf118c5a450aac2f222098e4fb1cf80d650**  /Users/me/Library/Caches/Homebrew/downloads/56649bcaba9bafb6c9437be368e2cc21b71e1657270394ec7290b1ca61eb0f7e--Therm-0.6.4.zip
```
So it appears someone noticed and did the work.  Thanks go out to them (and you!).

Anyways, I'm happy to checkout Therm now!

**Comment by trufae** [comment]
Cool thank you!
